voice_map_dict = {
    'af': ('af-ZA', 'af-ZA-AdriNeural', 'af-ZA-WillemNeural'),
    'am': ('am-ET', 'am-ET-MekdesNeural', 'am-ET-AmehaNeural'),
    'ar': ('ar-YE', 'ar-YE-MaryamNeural', 'ar-YE-SalehNeural'),
    'az': ('az-AZ', 'az-AZ-BanuNeural', 'az-AZ-BabekNeural'),
    'bg': ('bg-BG', 'bg-BG-KalinaNeural', 'bg-BG-BorislavNeural'),
    'bs': ('bs-BA', 'bs-BA-VesnaNeural', 'bs-BA-GoranNeural'),
    'ca': ('ca-ES', 'ca-ES-JoanaNeural', 'ca-ES-EnricNeural'),
    'cs': ('cs-CZ', 'cs-CZ-VlastaNeural', 'cs-CZ-AntoninNeural'),
    'cy': ('cy-GB', 'cy-GB-NiaNeural', 'cy-GB-AledNeural'),
    'da': ('da-DK', 'da-DK-ChristelNeural', 'da-DK-JeppeNeural'),
    'de': ('de-DE', 'de-DE-KatjaNeural', 'de-DE-ConradNeural'),
    'el': ('el-GR', 'el-GR-AthinaNeural', 'el-GR-NestorasNeural'),
    'es': ('es-VE', 'es-VE-PaolaNeural', 'es-VE-SebastianNeural'),
    'et': ('et-EE', 'et-EE-AnuNeural', 'et-EE-KertNeural'),
    'eu': ('eu-ES', 'eu-ES-AinhoaNeural', 'eu-ES-AnderNeural'),
    'fa': ('fa-IR', 'fa-IR-DilaraNeural', 'fa-IR-FaridNeural'),
    'fi': ('fi-FI', 'fi-FI-SelmaNeural', 'fi-FI-HarriNeural'),
    'fil': ('fil-PH', 'fil-PH-BlessicaNeural', 'fil-PH-AngeloNeural'),
    'ga': ('ga-IE', 'ga-IE-OrlaNeural', 'ga-IE-ColmNeural'),
    'gl': ('gl-ES', 'gl-ES-SabelaNeural', 'gl-ES-RoiNeural'),
    'gu': ('gu-IN', 'gu-IN-DhwaniNeural', 'gu-IN-NiranjanNeural'),
    'he': ('he-IL', 'he-IL-HilaNeural', 'he-IL-AvriNeural'),
    'hr': ('hr-HR', 'hr-HR-GabrijelaNeural', 'hr-HR-SreckoNeural'),
    'hu': ('hu-HU', 'hu-HU-NoemiNeural', 'hu-HU-TamasNeural'),
    'hy': ('hy-AM', 'hy-AM-AnahitNeural', 'hy-AM-HaykNeural'),
    'id': ('id-ID', 'id-ID-GadisNeural', 'id-ID-ArdiNeural'),
    'is': ('is-IS', 'is-IS-GudrunNeural', 'is-IS-GunnarNeural'),
    'it': ('it-IT', 'it-IT-ElsaNeural', 'it-IT-DiegoNeural'),
    'ja': ('ja-JP', 'ja-JP-NanamiNeural', 'ja-JP-KeitaNeural'),
    'jv': ('jv-ID', 'jv-ID-SitiNeural', 'jv-ID-DimasNeural'),
    'ka': ('ka-GE', 'ka-GE-EkaNeural', 'ka-GE-GiorgiNeural'),
    'kk': ('kk-KZ', 'kk-KZ-AigulNeural', 'kk-KZ-DauletNeural'),
    'km': ('km-KH', 'km-KH-SreymomNeural', 'km-KH-PisethNeural'),
    'ko': ('ko-KR', 'ko-KR-SunHiNeural', 'ko-KR-InJoonNeural'),
    'lo': ('lo-LA', 'lo-LA-KeomanyNeural', 'lo-LA-ChanthavongNeural'),
    'lt': ('lt-LT', 'lt-LT-OnaNeural', 'lt-LT-LeonasNeural'),
    'lv': ('lv-LV', 'lv-LV-EveritaNeural', 'lv-LV-NilsNeural'),
    'mk': ('mk-MK', 'mk-MK-MarijaNeural', 'mk-MK-AleksandarNeural'),
    'ml': ('ml-IN', 'ml-IN-SobhanaNeural', 'ml-IN-MidhunNeural'),
    'mn': ('mn-MN', 'mn-MN-YesuiNeural', 'mn-MN-BataaNeural'),
    'ms': ('ms-MY', 'ms-MY-YasminNeural', 'ms-MY-OsmanNeural'),
    'mt': ('mt-MT', 'mt-MT-GraceNeural', 'mt-MT-JosephNeural'),
    'my': ('my-MM', 'my-MM-NilarNeural', 'my-MM-ThihaNeural'),
    'nb': ('nb-NO', 'nb-NO-PernilleNeural', 'nb-NO-FinnNeural'),
    'ne': ('ne-NP', 'ne-NP-HemkalaNeural', 'ne-NP-SagarNeural'),
    'nl': ('nl-NL', 'nl-NL-FennaNeural', 'nl-NL-MaartenNeural'),
    'pl': ('pl-PL', 'pl-PL-AgnieszkaNeural', 'pl-PL-MarekNeural'),
    'ps': ('ps-AF', 'ps-AF-LatifaNeural', 'ps-AF-GulNawazNeural'),
    'pt': ('pt-PT', 'pt-PT-RaquelNeural', 'pt-PT-DuarteNeural'),
    'ro': ('ro-RO', 'ro-RO-AlinaNeural', 'ro-RO-EmilNeural'),
    'ru': ('ru-RU', 'ru-RU-SvetlanaNeural', 'ru-RU-DmitryNeural'),
    'si': ('si-LK', 'si-LK-ThiliniNeural', 'si-LK-SameeraNeural'),
    'sk': ('sk-SK', 'sk-SK-ViktoriaNeural', 'sk-SK-LukasNeural'),
    'sl': ('sl-SI', 'sl-SI-PetraNeural', 'sl-SI-RokNeural'),
    'so': ('so-SO', 'so-SO-UbaxNeural', 'so-SO-MuuseNeural'),
    'sq': ('sq-AL', 'sq-AL-AnilaNeural', 'sq-AL-IlirNeural'),
    'sr': ('sr-RS', 'sr-RS-SophieNeural', 'sr-RS-NicholasNeural'),
    'su': ('su-ID', 'su-ID-TutiNeural', 'su-ID-JajangNeural'),
    'sv': ('sv-SE', 'sv-SE-SofieNeural', 'sv-SE-MattiasNeural'),
    'sw': ('sw-TZ', 'sw-TZ-RehemaNeural', 'sw-TZ-DaudiNeural'),
    'ta': ('ta-SG', 'ta-SG-VenbaNeural', 'ta-SG-AnbuNeural'),
    'te': ('te-IN', 'te-IN-ShrutiNeural', 'te-IN-MohanNeural'),
    'th': ('th-TH', 'th-TH-PremwadeeNeural', 'th-TH-NiwatNeural'),
    'tr': ('tr-TR', 'tr-TR-EmelNeural', 'tr-TR-AhmetNeural'),
    'uk': ('uk-UA', 'uk-UA-PolinaNeural', 'uk-UA-OstapNeural'),
    'ur': ('ur-PK', 'ur-PK-UzmaNeural', 'ur-PK-AsadNeural'),
    'uz': ('uz-UZ', 'uz-UZ-MadinaNeural', 'uz-UZ-SardorNeural'),
    'vi': ('vi-VN', 'vi-VN-HoaiMyNeural', 'vi-VN-NamMinhNeural'),
    'wuu': ('wuu-CN', 'wuu-CN-XiaotongNeural', 'wuu-CN-YunzheNeural'),
    'yue': ('yue-CN', 'yue-CN-XiaoMinNeural,', 'yue-CN-YunSongNeural,'),
    'zh': ('zh-TW', 'zh-TW-HsiaoChenNeural', 'zh-TW-YunJheNeural'),
    'zu': ('zu-ZA', 'zu-ZA-ThandoNeural', 'zu-ZA-ThembaNeural'),
    "hi": ("hi-IN", 'hi-IN-SwaraNeural', 'hi-IN-MadhurNeural'),
    "en": ("en-US", 'en-US-JennyNeural', 'en-US-GuyNeural'),
    "bn": ("bn-IN", 'bn-IN-TanishaaNeural', 'bn-IN-BashkarNeural'),
    "fr": ("fr-FR", 'fr-FR-DeniseNeural', 'fr-FR-HenriNeural'),
    "kn": ("kn-IN", 'kn-IN-SapnaNeural', 'kn-IN-GaganNeural'),
    "mr": ("mr-IN", 'mr-IN-AarohiNeural', 'mr-IN-ManoharNeural'),
    "zh-Hans": ("zh-Hans", 'zh-CN-XiaoxiaoNeural', 'zh-CN-YunjianNeural')
}
lang_dict = {
    'Afrikaans': {'src': 'af-ZA', 'dest': 'af'},
    'Albanian': {'src': 'sq-AL', 'dest': 'sq'},
    'Amharic': {'src': 'am-ET', 'dest': 'am'},
    'Arabic': {'src': 'ar-YE', 'dest': 'ar'},
    'Armenian': {'src': 'hy-AM', 'dest': 'hy'},
    'Azerbaijani': {'src': 'az-AZ', 'dest': 'az'},
    'Bosnian (Latin)': {'src': 'bs-BA', 'dest': 'bs'},
    'Bulgarian': {'src': 'bg-BG', 'dest': 'bg'},
    'Cantonese (Traditional)': {'src': 'yue-CN', 'dest': 'yue'},
    'Catalan': {'src': 'ca-ES', 'dest': 'ca'},
    'Croatian': {'src': 'hr-HR', 'dest': 'hr'},
    'Czech': {'src': 'cs-CZ', 'dest': 'cs'},
    'Danish': {'src': 'da-DK', 'dest': 'da'},
    'Dutch': {'src': 'nl-NL', 'dest': 'nl'},
    'Estonian': {'src': 'et-EE', 'dest': 'et'},
    'Filipino': {'src': 'fil-PH', 'dest': 'fil'},
    'Finnish': {'src': 'fi-FI', 'dest': 'fi'},
    'German': {'src': 'de-DE', 'dest': 'de'},
    'Greek': {'src': 'el-GR', 'dest': 'el'},
    'Gujarati': {'src': 'gu-IN', 'dest': 'gu'},
    'Hebrew': {'src': 'he-IL', 'dest': 'he'},
    'Hungarian': {'src': 'hu-HU', 'dest': 'hu'},
    'Icelandic': {'src': 'is-IS', 'dest': 'is'},
    'Indonesian': {'src': 'id-ID', 'dest': 'id'},
    'Irish': {'src': 'ga-IE', 'dest': 'ga'},
    'Italian': {'src': 'it-IT', 'dest': 'it'},
    'Japanese': {'src': 'ja-JP', 'dest': 'ja'},
    'Kazakh': {'src': 'kk-KZ', 'dest': 'kk'},
    'Khmer': {'src': 'km-KH', 'dest': 'km'},
    'Korean': {'src': 'ko-KR', 'dest': 'ko'},
    'Lao': {'src': 'lo-LA', 'dest': 'lo'},
    'Latvian': {'src': 'lv-LV', 'dest': 'lv'},
    'Lithuanian': {'src': 'lt-LT', 'dest': 'lt'},
    'Malay': {'src': 'ms-MY', 'dest': 'ms'},
    'Malayalam': {'src': 'ml-IN', 'dest': 'ml'},
    'Maltese': {'src': 'mt-MT', 'dest': 'mt'},
    'Marathi': {'src': 'mr-IN', 'dest': 'mr'},
    'Myanmar': {'src': 'my-MM', 'dest': 'my'},
    'Nepali': {'src': 'ne-NP', 'dest': 'ne'},
    'Norwegian': {'src': 'nb-NO', 'dest': 'nb'},
    'Pashto': {'src': 'ps-AF', 'dest': 'ps'},
    'Persian': {'src': 'fa-IR', 'dest': 'fa'},
    'Polish': {'src': 'pl-PL', 'dest': 'pl'},
    'Portuguese (Brazil)': {'src': 'pt-PT', 'dest': 'pt'},
    'Romanian': {'src': 'ro-RO', 'dest': 'ro'},
    'Russian': {'src': 'ru-RU', 'dest': 'ru'},
    'Slovak': {'src': 'sk-SK', 'dest': 'sk'},
    'Slovenian': {'src': 'sl-SI', 'dest': 'sl'},
    'Spanish': {'src': 'es-VE', 'dest': 'es'},
    'Swahili': {'src': 'sw-TZ', 'dest': 'sw'},
    'Swedish': {'src': 'sv-SE', 'dest': 'sv'},
    'Tamil': {'src': 'ta-SG', 'dest': 'ta'},
    'Telugu': {'src': 'te-IN', 'dest': 'te'},
    'Thai': {'src': 'th-TH', 'dest': 'th'},
    'Turkish': {'src': 'tr-TR', 'dest': 'tr'},
    'Ukrainian': {'src': 'uk-UA', 'dest': 'uk'},
    'Urdu': {'src': 'ur-PK', 'dest': 'ur'},
    'Vietnamese': {'src': 'vi-VN', 'dest': 'vi'},
    'Welsh': {'src': 'cy-GB', 'dest': 'cy'},
    'English': {'src': 'en-US', 'dest': 'en'},
    'Kannada': {'src': 'kn-IN', 'dest': 'kn'},
    'Hindi': {'src': 'hi-IN', 'dest': 'hi'},
    'Bangla': {'src': 'bn-IN', 'dest': 'bn'},
    'French': {'src': 'fr-FR', 'dest': 'fr'},
    "Chinese(Mandarin)": {"src": "zh-Hans", "dest": "zh-Hans"}
}
auto_translate_dict = {
                # 'af-ZA': 'Afrikaans',
                # 'sq-AL': 'Albanian',
                # 'am-ET': 'Amharic',
                # 'ar-YE': 'Arabic',
                # 'hy-AM': 'Armenian',
                # 'az-AZ': 'Azerbaijani',
                # 'bs-BA': 'Bosnian (Latin)',
                # 'bg-BG': 'Bulgarian',
                # 'yue-CN': 'Cantonese (Traditional)',
                # 'ca-ES': 'Catalan',
                # 'hr-HR': 'Croatian',
                # 'cs-CZ': 'Czech',
                # 'da-DK': 'Danish',
                # 'nl-NL': 'Dutch',
                # 'et-EE': 'Estonian',
                # 'fil-PH': 'Filipino',
                # 'fi-FI': 'Finnish',
                # 'de-DE': 'German',
                # 'el-GR': 'Greek',
                # 'gu-IN': 'Gujarati',
                # 'he-IL': 'Hebrew',
                # 'hu-HU': 'Hungarian',
                # 'is-IS': 'Icelandic',
                # 'id-ID': 'Indonesian',
                # 'ga-IE': 'Irish',
                # 'it-IT': 'Italian',
                # 'ja-JP': 'Japanese',
                # 'kk-KZ': 'Kazakh',
                # 'km-KH': 'Khmer',
                # 'ko-KR': 'Korean',
                # 'lo-LA': 'Lao',
                # 'lv-LV': 'Latvian',
                # 'lt-LT': 'Lithuanian',
                # 'ms-MY': 'Malay',
                # 'ml-IN': 'Malayalam',
                # 'mt-MT': 'Maltese',
                # 'mr-IN': 'Marathi',
                # 'my-MM': 'Myanmar',
                # 'ne-NP': 'Nepali',
                # 'nb-NO': 'Norwegian',
                # 'ps-AF': 'Pashto',
                # 'fa-IR': 'Persian',
                # 'pl-PL': 'Polish',
                # 'pt-PT': 'Portuguese (Brazil)',
                # 'ro-RO': 'Romanian',
                # 'ru-RU': 'Russian',
                # 'sk-SK': 'Slovak',
                # 'sl-SI': 'Slovenian',
                # 'es-VE': 'Spanish',
                # 'sw-TZ': 'Swahili',
                # 'sv-SE': 'Swedish',
                # 'ta-SG': 'Tamil',
                # 'te-IN': 'Telugu',
                # 'th-TH': 'Thai',
                # 'tr-TR': 'Turkish',
                # 'uk-UA': 'Ukrainian',
                # 'ur-PK': 'Urdu',
                # 'vi-VN': 'Vietnamese',
                # 'cy-GB': 'Welsh',
                'en-US': 'English',
                'kn-IN': 'Kannada',
                'hi-IN': 'Hindi',
                'bn-IN': 'Bangla',
                # 'fr-FR': 'French',
                # 'zh-Hans': 'Chinese(Mandarin)'
            }
